server {
    listen 80;
    server_name playworksnorth.com www.playworksnorth.com;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        alias /root/playworksnorth.com/staticfiles/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/playworksnorth.sock;
    }
}
